name: Deploy ProduseSiServicii on EC2 instance
on:
  push:
    branches:
    - master
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: rsync over ssh
      env: 
        NODE_ENV: ${{secrets.NODE_ENV}}
        SPRING_ENV: ${{secrets.SPRING_ENV}}
        JDBC_DATABASE_URL: ${{secrets.JDBC_DATABASE_URL}}
        JDBC_DATABASE_NAME: ${{secrets.JDBC_DATABASE_NAME}}
        JDBC_DATABASE_PORT: ${{secrets.JDBC_DATABASE_PORT}}
        JDBC_DATABASE_USERNAME: ${{secrets.JDBC_DATABASE_USERNAME}}
        JDBC_DATABASE_PASSWORD: ${{secrets.JDBC_DATABASE_PASSWORD}}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
        AWS_S3_REGION: ${{secrets.AWS_S3_REGION}}
        FACEBOOK_APP_ID: ${{secrets.FACEBOOK_APP_ID}}
        FACEBOOK_SECRET: ${{secrets.FACEBOOK_SECRET}}
        SPRING_APP_STRIPE: ${{secrets.SPRING_APP_STRIPE}}
        SPRING_APP_FRONTEND_1: ${{secrets.SPRING_APP_FRONTEND_1}}
        SPRING_APP_FRONTEND_2: ${{secrets.SPRING_APP_FRONTEND_2}}
        SPRING_APP_TOKEN_SECRET_REFRESH_TOKEN: ${{secrets.SPRING_APP_TOKEN_SECRET_REFRESH_TOKEN}}
        SPRING_APP_TOKEN_SECRET_ACCESS_TOKEN: ${{secrets.SPRING_APP_TOKEN_SECRET_ACCESS_TOKEN}}
        SPRING_APP_TOKEN_SECRET_CHANGE_PASSWORD: ${{secrets.SPRING_APP_TOKEN_SECRET_CHANGE_PASSWORD}}
        SPRING_APP_TOKEN_SECRET_CHANGE_INFO: ${{secrets.SPRING_APP_TOKEN_SECRET_CHANGE_INFO}}
        EMAIL_APP_PASS: ${{secrets.EMAIL_APP_PASS}}
        CRYPT_KEY: "${{secrets.CRYPT_KEY}}"
      run: sh ./deploy_to_aws.sh
